# Generated by Django 4.2.6 on 2024-02-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_income_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
