# Generated by Django 4.2.6 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_alter_expense_category_alter_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='expense', max_length=10),
        ),
    ]
